databases:
  - name: with Rugby_DB
    databaseName: with_rugby_db
    user: with Rugby
    region: singapore

services:
  - type: web
    name: with Rugby
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: with Rugby_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

